### ISSUE TITLE
Remove potentially sensitive information from App.config

### ISSUE THREAD

**Issue by kant2002** [aodegov/mc_parser#5]
Is it possible to remove sensitive information from `NotesConnStr` configuration parameter, and use `Integrated Security=True` for connection setting, and use `.` instead of `MC-HOST`. That way it will work implicitly on the developer workstation, assuming SQL Server Express is installed.

**Comment by mcblacksea** [comment]
Yes, I agree that's good point.
Although, it was created by customer agreement.
But anyway, I like your suggestion and I've changed the app.config by the right way.
At least it will be OK for the development process.
Please pull my latest changes
